### ISSUE TITLE
Skin texure error.

### ISSUE THREAD

**Issue by fr1g** [mchorse/emoticons#14]
Hello,
I just found some error happened while I'm using the newest version of this mod you just uploaded to Curseforge for Minecraft 1.12.2. I'm using the recommended version of Forge,Optifine U F5.
#### About the problem I found:
Some places' texure of player's skin displaying transparency unexpectedly, (not only head, but also other places like the end of legs, and the problem on head is the most serious. And while armed armor, the armor's texure also not look right.)(as my screenshot below.)
![image](https://user-images.githubusercontent.com/53085628/83023038-fa9a2f00-a05e-11ea-99a5-79a1b0eda970.png)
Emoticons is a great mod that can made my "life" in Minecraft softly and cute,if you can fix these kind "small problems" , I will really appreciate it.
Wish you have nice days. 

F.

**Comment by fr1g** [comment]
by the way, while running,the tool or the weapon in hand will "stick into brain" by arms waving...

**Comment by mchorse** [comment]
Honestly, I don't see any problem there...

**Comment by fr1g** [comment]
im using a 3d skin with a overlaid texture...some place are showing  transparently at some place

BUT I SOLVED IT BY ROLL BACK TO EARLIER VERSION EMOTICONS！
ye.
Sent from my iPhone

On Sep 5, 2020, at 21:44, McHorse <notifications@github.com> wrote:

﻿

Honestly, I don't see any problem there...

**Comment by mchorse** [comment]
If that works, I suppose awesome! 👍
