### ISSUE TITLE
Installing on server side with non-mandatory installation on client side?

### ISSUE THREAD

**Issue by Lgmrszd** [mchorse/emoticons#21]
Use-case scenario: You're hosting modpack, and some players want to install Emoticons and see each other emotes. This would require this mod to be on the server. However, this will also require all players to install it on their clients, even if other players do not want to use this or other cosmetic/qol mods for faster loading times.

**Comment by mchorse** [comment]
That’s how Emoticons 0.5 and below worked, but it turned to be too problematic to be used with SpongeForge (or similar mods that add support with server environment), so I removed it in 0.6.

You can implement your own plugin, mod that will be listening and sending packets to `Emoticons` payload channel. See [this release’s change log](https://www.curseforge.com/minecraft/mc-mods/emoticons/files/2798999).

**Comment by Lgmrszd** [comment]
Thanks for informing that quickly. Could you please also update CurseForge page to state that installing on server side requires client side to have a mod as well?

**Comment by mchorse** [comment]
Hm, alright, although that should be obvious, but oh well...
