### ISSUE TITLE
Issue with some shaders

### ISSUE THREAD

**Issue by LeioceraYT** [mchorse/emoticons#23]
Issues with some shaders (Nostalgia, Simplicissimus)

There is a distortion at the arm, why?

https://www.youtube.com/watch?v=ti4_9CT8B74

**Comment by mchorse** [comment]
You’re saying this as I did it on purpose... 😅 

I’ve been wondering this for years myself, but I don’t know. It’s an issue with the shader pack and not my mod. 

You can try turning on simpler models in the Ctrl + 0 > Emoticons, but beside that, I can’t help. Feel free to find the shader’s dev and submit this bug to them.

**Comment by LeioceraYT** [comment]
I sent this issue already to the shaderpack developer. He / she said "it's a mod bug".

**Comment by LeioceraYT** [comment]
But thx for the answer

**Comment by mchorse** [comment]
Ah yes, instead of looking into it, they just say “it’s a mod bug.” 😔 

From my past experiments, this issue happens due TAA feature of the shader packs.

**Comment by LeioceraYT** [comment]
No change if I turn TAA off

![image](https://user-images.githubusercontent.com/65770087/94999956-46388880-05bd-11eb-91f4-8e1218058675.png)

**Comment by LeioceraYT** [comment]
![image](https://user-images.githubusercontent.com/65770087/95000396-9ebd5500-05c0-11eb-8354-5f95eb5bd3c4.png)

**Comment by LeioceraYT** [comment]
So, how can I fix it? Can I fix it?
