### ISSUE TITLE
Some polygons don't render.

### ISSUE THREAD

**Issue by NacroniSpongyTeam** [mchorse/emoticons#32]
This client was running with mods: "Backpacked", "CDM", "CFM", "CGM", "MinecraftCapes", "Obfuscate", "OptiFine", and "vehicle". I opened the menu for emotes and suddenly some polygons were missing from my skin. It could be "MinecraftCapes", "Obfuscate", or "OptiFine". I both ran 0.7 and 0.5 with their appropriate McLib requirements, and the issue still happened. I'm not sure why, but I'll run Crayfish mods that don't require Obfuscate.*

**Comment by NacroniSpongyTeam** [comment]
*if thats causing the problem.

**Comment by mchorse** [comment]
I can't tell what's the issue without a screenshot...

**Comment by NacroniSpongyTeam** [comment]
![lazy modeling](https://user-images.githubusercontent.com/60831747/110795433-d5208f80-8244-11eb-9e3b-50ac8c404fb3.png)
Okay, heres a screenshot.

**Comment by NacroniSpongyTeam** [comment]
I'm using McLib 2.2.2 and Emoticons 0.7, being those two the latest versions, and this happened to the model. Even 0.5 had the bug too, meaning it wasn't Emoticons or McLib's fault, it was other mods that configured the character model, like Obfuscate, MrCrayFish made it so it was easier to move body parts in his mod, or OptiFine, that optimizes Minecraft.

**Comment by mchorse** [comment]
Then I’m honestly unsure. I never seen such issue before. I’d say that if it still happens without other mods, i.e. McLib and Emoticons, it’s a graphics card issue or something like that.

**Comment by NacroniSpongyTeam** [comment]
Okay, I'll test without Obfuscate and/or OptiFine to see if the problem persists.

**Comment by NacroniSpongyTeam** [comment]
Yeah, I loaded Minecraft with 3 mods "McLib 2.2.2", "Emoticons 0.7", and "MinecraftCapes". It may be a graphics card issue, and I don't want to piss off Nvidia, so I'll just not use Emoticons for some time.

**Comment by NacroniSpongyTeam** [comment]
Its a skin problem. My main skin has transparency, and the updated skin texture, so that may be the problem, but using Steve, the skin works just fine without polygon errors. So, it may be a model or a texture error.
![trans bug](https://user-images.githubusercontent.com/60831747/110824714-4cfcb300-8261-11eb-9500-99e7d0ba968c.png)

**Comment by mchorse** [comment]
Ohh... that’s so interesting, thanks for reporting back! I don’t think it’s possible to fix though...
