### ISSUE TITLE
Problem and a Question

### ISSUE THREAD

**Issue by xFixx-official** [mchorse/emoticons#39]
Hello I have a question and a problem come first to the question would it work if you could add a function that the skin when I turn on Disable non-emote animations that the skin also remains 3D? and the problem is you see in the screenshot 
![2021-07-26_12 55 16]
(https://user-images.githubusercontent.com/82741955/126978397-e9080972-c351-46af-8b2b-4fb58d991340.png)

1.8.9
Emoticons 0.6.1 (for 1.8.9)

**Comment by mchorse** [comment]
Semi-transparency don’t work with Emoticons. You need to remove any transparency on the outer layer (maybe it’s a 99% transparency). 

And I don’t work on this mod (or any other beside Mappet) anymore, nor it will go open source.
