### ISSUE TITLE
Can you optimize swimming animation?

### ISSUE THREAD

**Issue by Abo233** [mchorse/emoticons#4]
1.The default swimming sprint trigger animation 
（The default swimming sprint trigger animation）

2.Do not look good. Swimming animation.

**Comment by mchorse** [comment]
Optimize? Do you mean improve?

**Comment by Abo233** [comment]
do the backstroke; swim the backstroke

**Comment by Abo233** [comment]
Trigger condition：
1.Three Leagues under the water
2.Sprint

**Comment by mchorse** [comment]
Nah, I don't really want to do it, maybe in the future.
