### ISSUE TITLE
Armors with custom model gets bugged

### ISSUE THREAD

**Issue by Adrigamer2950** [mchorse/emoticons#40]
With botania, or any mod that have a custom model in a armor makes the armor destroyed, yeah, i know that disabling the non-emote animations the bug gets resolved, but with the non-emotes animations disabled this is what happens
![2021-07-28_13 53 54](https://user-images.githubusercontent.com/58531641/127317927-e414643c-69c5-48a0-be5f-444dd8dc929e.png)

**Comment by mchorse** [comment]
As #10 and #9 say, it's not fixable. You can disable Emoticons' animations in Ctrl + 0, Emoticons and enable `Disable non-emote animations` option, but beside that, there is nothing can be done to make custom armors work with Emoticons.

**Comment by Adrigamer2950** [comment]
well, I think that's fixable, beacuse in the Mo' Bends mod it works perfectly with the animations and the armor

**Comment by mchorse** [comment]
That's cool that iwoplaza managed to make the armors work with his mod, but regardless of whether it's fixable, I'm not modding anymore. I'm finishing my last mod, and then I'm done with modding.
