### ISSUE TITLE
[question] is this mod compatible with More Player Models or Smart Moving?

### ISSUE THREAD

**Issue by HowardZHY** [mchorse/emoticons#53]

**Comment by mchorse** [comment]
Depends on what do you mean by compatibility. Will it crash when installed together? No. Will Emoticons’ model work with MorePlayerModels’ actions (sit, lying, etc.) or Smart Moving’ mechanics (climbing ladders, crawling, etc.)? Also no, there is no way to make it work.

Hopefully it answers.
