### ISSUE TITLE
Emoticons Prevent Skin Layers 3D From Working

### ISSUE THREAD

**Issue by JustDesoroxxx** [mchorse/emoticons#55]
Hi, Emoticons prevent [Skin Layers 3D] from working in 1.12.2.

The mod works fine in first person but in third person the mod just don't work Emoticons work fine.

[Skin Layers 3D]: https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d

**Comment by Chryfi** [comment]
Such mods can not work with Emoticons, because Emoticons uses its own models. This is impossible to fix. Also, there is an emoticons model with 3D layer (for example default_3D morph) so you don't need that other mod.

**Comment by JustDesoroxxx** [comment]
How can I use the default 3D layer of emoticon?

**Comment by Chryfi** [comment]
By using the default_3d morph or slim_3d

**Comment by JustDesoroxxx** [comment]
Where can I do that? Is that in the Metamorph mod?

**Comment by Chryfi** [comment]
You can do that in Metamorph mod by morphing into it, or you can change the default model in Emoticons settings (Ctrl+0)

**Comment by JustDesoroxxx** [comment]
Okay thanks you!
