### ISSUE TITLE
Can i will this mod Handle to the minecraft The Chinese version?

### ISSUE THREAD

**Issue by XiaoMoJun521** [mchorse/emoticons#56]
I want to will this in minecraft the Chinese vresion （QAQ）

**Comment by XiaoMoJun521** [comment]
umm....e isreprinted not is Handle

**Comment by Chryfi** [comment]
I don't understand

**Comment by Chryfi** [comment]
I researched a bit... so I assume you want to play emoticons in the Chinese Minecraft version from NetEase. You need to install forge, if you can't install forge for that Minecraft then you cannot run Emoticons.

**Comment by XiaoMoJun521** [comment]
why i play other Need to be forge Does not affect the

**Comment by XiaoMoJun521** [comment]
Maybe I can try

**Comment by XiaoMoJun521** [comment]
Wait the forge is McLib？

**Comment by XiaoMoJun521** [comment]
Or what？

**Comment by Chryfi** [comment]
No. You need to install forge for Minecraft 1.12.2 https://files.minecraftforge.net/net/minecraftforge/forge/

**Comment by XiaoMoJun521** [comment]
okay

**Comment by XiaoMoJun521** [comment]
umm...Under this How to author authorization？

**Comment by XiaoMoJun521** [comment]
Can't find（Ｏ(≧口≦)Ｏ）

**Comment by Chryfi** [comment]
I dont understand what the problem is.

**Comment by XiaoMoJun521** [comment]
ah okay Where the author authorization？

**Comment by XiaoMoJun521** [comment]
Not very can speak English
so...umm..you know
I am a Chinese

**Comment by XiaoMoJun521** [comment]
ah...ok I in this week Wanted to think

**Comment by XiaoMoJun521** [comment]
I tried to put this mod in the mods folder
Successful import

**Comment by XiaoMoJun521** [comment]
I succeeded in Chinese Minecraft play this mod

**Comment by XiaoMoJun521** [comment]
emm...You allow I put this mod Uploaded to the Chinese Minecraft？

**Comment by XiaoMoJun521** [comment]
@Chryfi

**Comment by XiaoMoJun521** [comment]
oh right and Mclib

**Comment by Chryfi** [comment]
> emm...You allow I put this mod Uploaded to the Chinese Minecraft？

You don't need my permission to play Minecraft mods... I am confused...

**Comment by XiaoMoJun521** [comment]
no Chinese Minecraft Without this mod
I want to upload this mod in Chinese Minecraft
And I need your allow upload this mod

**Comment by Chryfi** [comment]
You can play with this mod in any Minecraft

**Comment by Chryfi** [comment]
@mchorse this is your mod, you have to give permission :)

**Comment by mchorse** [comment]
To be honest, I don't want my mods to be distributed on other platforms. Permission is not granted.

**Comment by XiaoMoJun521** [comment]
So I ask

**Comment by XiaoMoJun521** [comment]
This mod has not been uploaded

**Comment by Chryfi** [comment]
McHorse has not given permission to distribute the mods on other platforms.

**Comment by XiaoMoJun521** [comment]
right I need to McHorse permission
