### ISSUE TITLE
Incompatibility with Wings and Armourer's Workshop mods

### ISSUE THREAD

**Issue by Eduuu1631** [mchorse/emoticons#58]
When the Emoticons mod is used there is interference in the Wings and Armourer's Workshop mods, where the textures of the wings and any clothing do not load.
![image](https://user-images.githubusercontent.com/119682627/205316563-17fbb0ca-b364-467b-bab4-5d657a81f9ee.png)

**Comment by Chryfi** [comment]
Emoticons renders its own models. We can't add compatibility for these mods.
