### ISSUE TITLE
I have an issue with the fact that you won't update this mod to 1.8.9

### ISSUE THREAD

**Issue by MochaFrappuccino** [mchorse/emoticons#8]
1.8.9 is NOT a dead version. Although 1.12.2 may be the most popular version for modding, 1.8.9 is the most popular for pvp. For these reasons I ask you to update this mod to 1.8.9

**Comment by MochaFrappuccino** [comment]
To add on to the fact that 1.8.9 is the best version for pvp many people would apriciate the fact that they could use emotes without using a pvp client.

**Comment by dsweber2** [comment]
why don't you put in the leg work of updating it instead of just demanding that they spend their time catering to your interests. This is not the point of issues

**Comment by mchorse** [comment]
Oh, right, I forgot to close this issue 😂 

I'm not interested in spending my time into porting the mod on an older version. It's just too much work, boring and bluntly speaking waste of time, as I don't get anything in return.

**Comment by MochaFrappuccino** [comment]
But like I said so many people would love it! I would even switch from Badlion to forge again.
