### ISSUE TITLE
Armor Renderig Issues 

### ISSUE THREAD

**Issue by PresquePlayed** [mchorse/emoticons#9]
This mod messes up the rendering of 3d Armors, I know you stated that you wouldn't fix compability with mods but if this issues would be fixed this od would be amazing in a heavily modded enviroment

**Comment by mchorse** [comment]
Sorry, this is just **impossible** to fix.

**Comment by fr1g** [comment]
> Sorry, this is just **impossible** to fix.

hey there...
I found Mo'Bend has fixed this bug recently. Sorry I don't know if your mods  use different ways to make player's module soft,but I still think you can try to figure out how mo'bends did that... maybe it's a key to fix it.

**Comment by mchorse** [comment]
> > Sorry, this is just **impossible** to fix.
> 
> hey there...
> I found Mo'Bend has fixed this bug recently. Sorry I don't know if your mods use different ways to make player's module soft,but I still think you can try to figure out how mo'bends did that... maybe it's a key to fix it.

We did it completely differently. There is no way to use Mo' Bends' technique to use it with my mods. Regardless of whether it was possible, I'm quitting Minecraft modding so I won't be fixing it anyway.
